import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { joinShopDb, parseInvShops, parseNpcKeepers, parseObjDefs, type ParsedInv, type ParsedKeeper, type ParsedObj } from './parse.js';

const CONTENT = process.env.CONTENT_DIR ?? join(homedir(), 'code', 'rs2b2t-engine', '..', 'rs2b2t-content');
const OUT = 'src/bot/data/shopdb.ts';

function filesUnder(root: string, ext: string): string[] {
    return (readdirSync(root, { recursive: true }) as string[])
        .filter(f => f.endsWith(ext))
        .map(f => join(root, f))
        .sort();
}

function generate(): string {
    const scripts = join(CONTENT, 'scripts');
    const invs: ParsedInv[] = filesUnder(scripts, '.inv').flatMap(f => parseInvShops(readFileSync(f, 'utf8')));
    const keepers: ParsedKeeper[] = filesUnder(scripts, '.npc').flatMap(f => parseNpcKeepers(readFileSync(f, 'utf8')));
    const objs: Record<string, ParsedObj> = {};
    for (const f of filesUnder(scripts, '.obj')) {
        Object.assign(objs, parseObjDefs(readFileSync(f, 'utf8')));
    }
    const db = joinShopDb(invs, keepers, objs);
    const ordered = Object.keys(db).sort().map(k => `    ${JSON.stringify(k)}: ${JSON.stringify(db[k])}`);
    console.log(`shops=${ordered.length} invsWithStock=${invs.length} keepers=${keepers.length}`);
    return [
        '/* eslint-disable */',
        '// GENERATED by tools/shops/gen-shopdb.ts, do not edit.',
        '// Regenerate: bun tools/shops/gen-shopdb.ts   (drift gate: --check)',
        "import type { ShopRecord } from '#/bot/api/shop/types.js';",
        '',
        'export const SHOP_DB: Record<string, ShopRecord> = {',
        ordered.join(',\n'),
        '};',
        ''
    ].join('\n');
}

const fresh = generate();
if (process.argv.includes('--check')) {
    let current = '';
    try {
        current = readFileSync(OUT, 'utf8');
    } catch {
        // Missing output is stale.
    }
    if (current !== fresh) {
        console.error(`STALE: ${OUT} does not match the content pack — run: bun tools/shops/gen-shopdb.ts`);
        process.exit(1);
    }
    console.log(`ok: ${OUT} matches the content pack`);
} else {
    writeFileSync(OUT, fresh);
    console.log(`wrote ${OUT}`);
}
