/* eslint-disable */
// GENERATED by tools/combat/gen-spelldb.ts, do not edit.
// Regenerate: bun tools/combat/gen-spelldb.ts   (drift gate: --check)

export interface SpellRow {
    /** staff_spells:ssbN autocast button index (com id 1830 + ssb). */
    ssb: number;
    level: number;
    /** Per-cast rune costs by display name, before staff substitution. */
    runes: { rune: string; count: number }[];
}

/** Autocastable combat spells by display name (staff_spells layout). */
export const SPELL_DB: Record<string, SpellRow> = {
    "Wind Strike": {"ssb":0,"level":1,"runes":[{"rune":"Mind rune","count":1},{"rune":"Air rune","count":1}]},
    "Water Strike": {"ssb":1,"level":5,"runes":[{"rune":"Mind rune","count":1},{"rune":"Water rune","count":1},{"rune":"Air rune","count":1}]},
    "Earth Strike": {"ssb":2,"level":9,"runes":[{"rune":"Mind rune","count":1},{"rune":"Earth rune","count":2},{"rune":"Air rune","count":1}]},
    "Fire Strike": {"ssb":3,"level":13,"runes":[{"rune":"Mind rune","count":1},{"rune":"Fire rune","count":3},{"rune":"Air rune","count":2}]},
    "Wind Bolt": {"ssb":4,"level":17,"runes":[{"rune":"Chaos rune","count":1},{"rune":"Air rune","count":2}]},
    "Water Bolt": {"ssb":5,"level":23,"runes":[{"rune":"Chaos rune","count":1},{"rune":"Water rune","count":2},{"rune":"Air rune","count":2}]},
    "Earth Bolt": {"ssb":6,"level":29,"runes":[{"rune":"Chaos rune","count":1},{"rune":"Earth rune","count":3},{"rune":"Air rune","count":2}]},
    "Fire Bolt": {"ssb":7,"level":35,"runes":[{"rune":"Chaos rune","count":1},{"rune":"Fire rune","count":4},{"rune":"Air rune","count":3}]},
    "Wind Blast": {"ssb":8,"level":41,"runes":[{"rune":"Death rune","count":1},{"rune":"Air rune","count":3}]},
    "Water Blast": {"ssb":9,"level":47,"runes":[{"rune":"Death rune","count":1},{"rune":"Water rune","count":3},{"rune":"Air rune","count":3}]},
    "Earth Blast": {"ssb":10,"level":53,"runes":[{"rune":"Death rune","count":1},{"rune":"Earth rune","count":4},{"rune":"Air rune","count":3}]},
    "Fire Blast": {"ssb":11,"level":59,"runes":[{"rune":"Death rune","count":1},{"rune":"Fire rune","count":5},{"rune":"Air rune","count":4}]},
    "Wind Wave": {"ssb":12,"level":62,"runes":[{"rune":"Blood rune","count":1},{"rune":"Air rune","count":5}]},
    "Water Wave": {"ssb":13,"level":65,"runes":[{"rune":"Blood rune","count":1},{"rune":"Water rune","count":7},{"rune":"Air rune","count":5}]},
    "Earth Wave": {"ssb":14,"level":70,"runes":[{"rune":"Blood rune","count":1},{"rune":"Earth rune","count":7},{"rune":"Air rune","count":5}]},
    "Fire Wave": {"ssb":15,"level":75,"runes":[{"rune":"Blood rune","count":1},{"rune":"Fire rune","count":7},{"rune":"Air rune","count":5}]}
};

/** Staff display name to the rune(s) it provides for free while wielded. */
export const STAFF_RUNES: Record<string, string[]> = {
    "Air battlestaff": ["Air rune"],
    "Earth battlestaff": ["Earth rune"],
    "Fire battlestaff": ["Fire rune"],
    "Lava battlestaff": ["Earth rune","Fire rune"],
    "Mystic air staff": ["Air rune"],
    "Mystic earth staff": ["Earth rune"],
    "Mystic fire staff": ["Fire rune"],
    "Mystic lava staff": ["Earth rune","Fire rune"],
    "Mystic water staff": ["Water rune"],
    "Staff of air": ["Air rune"],
    "Staff of earth": ["Earth rune"],
    "Staff of fire": ["Fire rune"],
    "Staff of water": ["Water rune"],
    "Water battlestaff": ["Water rune"]
};
