// Why: the Legends pockets' bounding boxes overlap, so the tile sets are flooded from the baked pack.

/** Emit `defs/legends/pockets.ts` as z-indexed x runs: `bun tools/nav/legends-pockets.ts > src/bot/api/ai/quests/defs/legends/pockets.ts`. */
import fs from 'node:fs';
import { gunzipSync } from 'fflate';

import doorsJson from '../../src/bot/event/webwalk/data/doors.json';
import stairsJson from '../../src/bot/event/webwalk/data/stairEdges.json';
import transportsJson from '../../src/bot/event/webwalk/data/transports.json';
import { PathFinder, type DoorEdgeData, type NavPoint } from '../../src/bot/event/webwalk/PathFinder.js';

let bytes: Uint8Array = new Uint8Array(fs.readFileSync('out/collision.lcnav.gz'));
if (bytes[0] === 0x1f && bytes[1] === 0x8b) {
    bytes = gunzipSync(bytes);
}
const finder = new PathFinder(bytes);
finder.addEdges(doorsJson as DoorEdgeData[], transportsJson as never, stairsJson);

const DX = [0, 1, 0, -1, 1, 1, -1, -1];
const DZ = [1, 0, -1, 0, 1, -1, -1, 1];
const nodeId = (x: number, z: number, level: number): number => (level << 28) | (x << 14) | z;
const edges: Map<number, { to: number }[]> = (finder as unknown as { edges: Map<number, { to: number }[]> }).edges;

function flood(seed: NavPoint): Set<number> {
    const seen = new Set<number>([nodeId(seed.x, seed.z, seed.level)]);
    const stack = [...seen];
    while (stack.length > 0) {
        const cur = stack.pop()!;
        const x = (cur >> 14) & 0x3fff;
        const z = cur & 0x3fff;
        const level = (cur >> 28) & 0x3;
        const mask = finder.exitMask(x, z, level);
        for (let d = 0; d < 8; d++) {
            if ((mask & (1 << d)) === 0) {
                continue;
            }
            const next = nodeId(x + DX[d], z + DZ[d], level);
            if (!seen.has(next)) {
                seen.add(next);
                stack.push(next);
            }
        }
        for (const edge of edges.get(cur) ?? []) {
            if (!seen.has(edge.to)) {
                seen.add(edge.to);
                stack.push(edge.to);
            }
        }
    }
    return seen;
}

/** One seed per pocket, each taken from a tile the quest stands on. */
const POCKETS: readonly [string, NavPoint][] = [
    ['shamanCave', { x: 2773, z: 9341, level: 0 }],
    ['octagram', { x: 2792, z: 9328, level: 0 }],
    ['crevice', { x: 2800, z: 9340, level: 0 }],
    ['outerGate', { x: 2809, z: 9331, level: 0 }],
    ['boulderOne', { x: 2809, z: 9325, level: 0 }],
    ['boulderTwo', { x: 2809, z: 9321, level: 0 }],
    ['innerGate', { x: 2809, z: 9317, level: 0 }],
    ['trials', { x: 2809, z: 9313, level: 0 }],
    ['wallRoom', { x: 2789, z: 9296, level: 0 }],
    ['gemRoom', { x: 2774, z: 9301, level: 0 }],
    ['winchRoom', { x: 2763, z: 9320, level: 0 }],
    ['viyeldiLedge', { x: 2377, z: 4712, level: 0 }],
    ['descentOne', { x: 2376, z: 4717, level: 0 }],
    ['descentTwo', { x: 2378, z: 4728, level: 0 }],
    ['descentThree', { x: 2382, z: 4728, level: 0 }],
    ['descentFour', { x: 2388, z: 4728, level: 0 }],
    ['descentFive', { x: 2390, z: 4723, level: 0 }],
    ['viyeldiMain', { x: 2390, z: 4717, level: 0 }],
    ['viyeldiSource', { x: 2421, z: 4689, level: 0 }]
];

function runsOf(tiles: Set<number>): [number, number, number][] {
    const byZ = new Map<number, number[]>();
    for (const id of tiles) {
        const x = (id >> 14) & 0x3fff;
        const z = id & 0x3fff;
        const row = byZ.get(z) ?? [];
        row.push(x);
        byZ.set(z, row);
    }
    const runs: [number, number, number][] = [];
    for (const z of [...byZ.keys()].sort((a, b) => a - b)) {
        const xs = byZ.get(z)!.sort((a, b) => a - b);
        let start = xs[0]!;
        let prev = start;
        for (const x of xs.slice(1)) {
            if (x !== prev + 1) {
                runs.push([z, start, prev]);
                start = x;
            }
            prev = x;
        }
        runs.push([z, start, prev]);
    }
    return runs;
}

const seen = new Map<string, string>();
const lines: string[] = [];
for (const [name, seed] of POCKETS) {
    const tiles = flood(seed);
    const key = [...tiles].sort((a, b) => a - b)[0];
    if (seen.has(String(key))) {
        throw new Error(`${name} floods the same component as ${seen.get(String(key))}`);
    }
    seen.set(String(key), name);
    const runs = runsOf(tiles);
    lines.push(`    ${name}: [${runs.map(r => `[${r[0]},${r[1]},${r[2]}]`).join(', ')}]`);
}

process.stdout.write(`// GENERATED by tools/nav/legends-pockets.ts, do not edit.
// Regenerate: bun tools/nav/legends-pockets.ts > src/bot/api/ai/quests/defs/legends/pockets.ts

// Why: every pocket below is sealed in the baked pack and joined to its neighbours only by a scripted crossing, and their bounding boxes overlap, so tiles are classified by the flood.

/** Each pocket's tiles as \`[z, xFrom, xTo]\` runs, flooded from the collision pack. */
export const LEGENDS_POCKETS = {
${lines.join(',\n')}
} as const;

export type LegendsPocket = keyof typeof LEGENDS_POCKETS;

/** Which sealed pocket a tile is in, or null when it is on open ground. */
export function legendsPocket(tile: { x: number; z: number; level: number } | null | undefined): LegendsPocket | null {
    if (!tile || tile.level !== 0) {
        return null;
    }
    for (const [name, runs] of Object.entries(LEGENDS_POCKETS) as [LegendsPocket, readonly (readonly number[])[]][]) {
        for (const run of runs) {
            if (run[0] === tile.z && tile.x >= run[1]! && tile.x <= run[2]!) {
                return name;
            }
        }
    }
    return null;
}
`);
