import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const CONTENT = process.env.CONTENT_DIR ?? join(homedir(), 'code', 'rs2b2t-content');
const OUT = 'src/bot/data/dropdb.ts';
const DROP_DIR = join(CONTENT, 'scripts', 'drop tables', 'scripts');

function filesUnder(root: string, ext: string): string[] {
    return (readdirSync(root, { recursive: true }) as string[])
        .filter(f => f.endsWith(ext))
        .map(f => join(root, f))
        .sort();
}

function loadConfigNames(ext: string, extra?: (cur: string, line: string) => void): Map<string, string> {
    const files = filesUnder(join(CONTENT, 'scripts'), ext);
    const unpack = files.filter(f => f.includes('/_unpack/'));
    const canonical = files.filter(f => !f.includes('/_unpack/'));
    const names = new Map<string, string>();
    for (const f of [...unpack, ...canonical]) {
        let cur: string | null = null;
        for (const raw of readFileSync(f, 'utf8').split('\n')) {
            const line = raw.trim();
            const head = /^\[([a-z0-9_]+)\]$/.exec(line);
            if (head) {
                cur = head[1];
            } else if (cur && line.startsWith('name=')) {
                names.set(cur, line.slice('name='.length));
            } else if (cur) {
                extra?.(cur, line);
            }
        }
    }
    return names;
}

interface Block {
    type: string;
    name: string;
    body: string;
}

function loadBlocks(): Map<string, Block> {
    const blocks = new Map<string, Block>();
    for (const f of filesUnder(DROP_DIR, '.rs2')) {
        let cur: Block | null = null;
        const lines: string[] = [];
        const flush = (): void => { if (cur) { cur.body = lines.join('\n'); blocks.set(`${cur.type}:${cur.name}`, cur); lines.length = 0; } };
        for (const raw of readFileSync(f, 'utf8').split('\n')) {
            const head = /^\[([a-z0-9_]+)\s*,\s*([a-z0-9_]+)\]/.exec(raw.trim());
            if (head) {
                flush();
                cur = { type: head[1], name: head[2], body: '' };
            } else if (cur) {
                lines.push(raw);
            }
        }
        flush();
    }
    return blocks;
}

const objNames = loadConfigNames('.obj');
const deathDrops = new Map<string, string>();
const npcNames = loadConfigNames('.npc', (cur, line) => {
    if (line.startsWith('param=death_drop,')) {
        deathDrops.set(cur, line.slice('param=death_drop,'.length).split(',')[0].trim());
    }
});
const blocks = loadBlocks();

function itemsIn(key: string, deathDrop: string | undefined, seen: Set<string>): Set<string> {
    const out = new Set<string>();
    const block = blocks.get(key);
    if (!block || seen.has(key)) {
        return out;
    }
    seen.add(key);
    const tokens: string[] = [];
    for (const m of block.body.matchAll(/obj_add\s*\(\s*npc_coord\s*,\s*(~?[a-z0-9_]+)/g)) { tokens.push(m[1]); }
    for (const m of block.body.matchAll(/return\s*\(\s*(~?[a-z0-9_]+)/g)) { tokens.push(m[1]); }
    // megararetable stages its drop in a local ($drop = rune_spear; ... return ($drop, 1)), so the literal never follows `return (`. Non-obj tokens are filtered below.
    for (const m of block.body.matchAll(/=\s*([a-z][a-z0-9_]*)\s*;/g)) { tokens.push(m[1]); }
    for (const tok of tokens) {
        if (tok.startsWith('~')) {
            for (const it of itemsIn(`proc:${tok.slice(1)}`, deathDrop, seen)) { out.add(it); }
        } else if (tok === 'npc_param') {
            if (deathDrop) { out.add(deathDrop); }
        } else if (objNames.has(tok)) {
            out.add(tok);
        } else if (tok.startsWith('cert_') && objNames.has(tok.slice('cert_'.length))) {
            // noted forms are generated, so cert_<x> has no [cert_<x>] block to look up
            out.add(tok.slice('cert_'.length));
        }
    }
    return out;
}

function generate(): string {
    const byDisplay = new Map<string, Set<string>>();
    for (const block of blocks.values()) {
        if (!/^ai_queue/.test(block.type) || !npcNames.has(block.name)) {
            continue;
        }
        const items = itemsIn(`${block.type}:${block.name}`, deathDrops.get(block.name), new Set());
        if (items.size === 0) {
            continue;
        }
        const display = npcNames.get(block.name)!;
        const set = byDisplay.get(display) ?? new Set<string>();
        for (const it of items) {
            const name = objNames.get(it);
            if (name) { set.add(name); }
        }
        byDisplay.set(display, set);
    }

    const rows = [...byDisplay.entries()]
        .filter(([, set]) => set.size > 0)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([monster, set]) => `    ${JSON.stringify(monster)}: ${JSON.stringify([...set].sort())}`);

    return [
        '/* eslint-disable */',
        '// GENERATED by tools/combat/gen-dropdb.ts, do not edit.',
        '// Regenerate: bun tools/combat/gen-dropdb.ts   (drift gate: --check)',
        '',
        '/** Monster display name to the item display names its drop table can yield (direct drops, always-drop, and resolved herb/gem/jewel sub-tables). Powers the loot multi-select. */',
        'export const DROP_DB: Record<string, string[]> = {',
        rows.join(',\n'),
        '};',
        ''
    ].join('\n');
}

const text = generate();
if (process.argv.includes('--check')) {
    const current = (() => { try { return readFileSync(OUT, 'utf8'); } catch { return ''; } })();
    if (current !== text) {
        console.error(`${OUT} is stale — regenerate with: bun tools/combat/gen-dropdb.ts`);
        process.exit(1);
    }
    console.log(`${OUT} is up to date`);
} else {
    writeFileSync(OUT, text);
    console.log(`wrote ${OUT} (${(text.match(/^ {4}"/gm) ?? []).length} monsters)`);
}
