import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { joinItemDb, parseItemDefs, parseObjPack, type ParsedItem } from './parse.js';

const CONTENT = process.env.CONTENT_DIR ?? join(homedir(), 'code', 'rs2b2t-content');
const OUT = 'src/bot/data/itemdb.ts';

function filesUnder(root: string, ext: string): string[] {
    return (readdirSync(root, { recursive: true }) as string[])
        .filter(f => f.endsWith(ext))
        .map(f => join(root, f))
        .sort();
}

function generate(): string {
    const objs: Record<string, ParsedItem> = {};
    for (const f of filesUnder(join(CONTENT, 'scripts'), '.obj')) {
        Object.assign(objs, parseItemDefs(readFileSync(f, 'utf8')));
    }
    const ids = parseObjPack(readFileSync(join(CONTENT, 'pack', 'obj.pack'), 'utf8'));
    const db = joinItemDb(objs, ids);
    const worn = db.filter(r => r.slot).length;
    console.log(`items=${db.length} worn=${worn} consumable=${db.length - worn}`);
    return [
        '/* eslint-disable */',
        '// GENERATED by tools/items/gen-itemdb.ts, do not edit.',
        '// Regenerate: bun tools/items/gen-itemdb.ts   (drift gate: --check)',
        "import type { ItemRecord } from '#/bot/api/loadout/types.js';",
        '',
        'export const ITEM_DB: ItemRecord[] = [',
        db.map(r => `    ${JSON.stringify(r)}`).join(',\n'),
        '];',
        ''
    ].join('\n');
}

const fresh = generate();
if (process.argv.includes('--check')) {
    let current = '';
    try {
        current = readFileSync(OUT, 'utf8');
    } catch {
        // Missing output is stale.
    }
    if (current !== fresh) {
        console.error(`STALE: ${OUT} does not match the content pack — run: bun tools/items/gen-itemdb.ts`);
        process.exit(1);
    }
    console.log(`ok: ${OUT} matches the content pack`);
} else {
    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, fresh);
    console.log(`wrote ${OUT}`);
}
