import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { parseObjPack } from './parse.js';

const CONTENT = process.env.CONTENT_DIR ?? join(homedir(), 'code', 'rs2b2t-content');
const OUT = 'src/bot/data/untradeable.ts';

function filesUnder(root: string, ext: string): string[] {
    return (readdirSync(root, { recursive: true }) as string[])
        .filter(f => f.endsWith(ext))
        .map(f => join(root, f))
        .sort();
}

/** Debugnames marked untradeable or dummy. */
// Why: objects are tradeable by default; only opcode 15 or dummyitem disables trading.
function untradeableNames(text: string): string[] {
    const out: string[] = [];
    let id: string | null = null;
    let off = false;
    const flush = (): void => {
        if (id !== null && off) {
            out.push(id);
        }
    };
    for (const raw of text.split('\n')) {
        const line = raw.trim();
        const head = /^\[([a-z0-9_]+)\]$/.exec(line);
        if (head) {
            flush();
            id = head[1]!;
            off = false;
        } else if (line === 'tradeable=no' || /^dummyitem=(?!0$)/.test(line)) {
            off = true;
        }
    }
    flush();
    return out;
}

function generate(): string {
    const names: string[] = [];
    for (const f of filesUnder(join(CONTENT, 'scripts'), '.obj')) {
        names.push(...untradeableNames(readFileSync(f, 'utf8')));
    }
    const ids = parseObjPack(readFileSync(join(CONTENT, 'pack', 'obj.pack'), 'utf8'));
    const resolved = [...new Set(names.map(n => ids.get(n)).filter((n): n is number => n !== undefined))].sort((a, b) => a - b);
    console.log(`untradeable names=${names.length} resolved=${resolved.length}`);

    const rows: string[] = [];
    for (let i = 0; i < resolved.length; i += 16) {
        rows.push(`    ${resolved.slice(i, i + 16).join(', ')}`);
    }
    return [
        '// GENERATED by tools/items/gen-untradeable.ts, do not edit.',
        '// Regenerate: bun tools/items/gen-untradeable.ts   (drift gate: --check)',
        '',
        '/** Objs the content marks untradeable, so no order book should offer to trade them. */',
        'export const UNTRADEABLE_IDS: readonly number[] = [',
        rows.join(',\n'),
        '];',
        ''
    ].join('\n');
}

const fresh = generate();
if (process.argv.includes('--check')) {
    let current = '';
    try {
        current = readFileSync(OUT, 'utf8');
    } catch {
        // Missing output is stale.
    }
    if (current !== fresh) {
        console.error(`STALE: ${OUT} does not match the content pack — run: bun tools/items/gen-untradeable.ts`);
        process.exit(1);
    }
    console.log(`ok: ${OUT} matches the content pack`);
} else {
    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, fresh);
    console.log(`wrote ${OUT}`);
}
