// Why: a revision bump renumbers ~150 opcodes; generate them from the engine and gate on drift (see test/io/protDrift.test.ts).

import { readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

export const DEFAULT_ENGINE_DIR = process.env.ENGINE_DIR ?? join(homedir(), 'code', 'rs2b2t-engine');

// Engine names mapped to client names; keep the existing Client.ts call sites.
const ALIAS: Record<string, string> = {
    IF_SETTAB: 'IF_SETICON',
    IF_SETTAB_ACTIVE: 'IF_SHOWICON',
    RESET_CLIENT_VARCACHE: 'VARP_SYNC',
    LOC_MERGE: 'P_LOCMERGE',
    REPORT_ABUSE: 'SEND_SNAPSHOT'
};

type Prot = { name: string; id: number; length: number };

function parse(source: string): Prot[] {
    const re = /static readonly ([A-Z0-9_]+) = new [A-Za-z]+\((-?\d+),\s*(-?\d+)\)/g;
    const out: Prot[] = [];
    for (const m of source.matchAll(re)) {
        out.push({ name: ALIAS[m[1]] ?? m[1], id: Number(m[2]), length: Number(m[3]) });
    }
    return out;
}

function renderEnum(name: string, prots: Prot[]): string {
    const body = prots.map(p => `    ${p.name} = ${p.id},`).join('\n');
    return `export const enum ${name} {\n${body}\n}\n`;
}

function renderSizes(prots: Prot[]): string {
    const sizes = new Array(256).fill(0);
    for (const p of prots) {
        sizes[p.id] = p.length;
    }
    const rows: string[] = [];
    for (let i = 0; i < 256; i += 10) {
        rows.push('    ' + sizes.slice(i, i + 10).join(', ') + ',');
    }
    return `export const ServerProtSizes = [\n${rows.join('\n')}\n];\n`;
}

export function parseRevision(worldConfigSource: string): number {
    const m = worldConfigSource.match(/revision:\s*(\d+)/);
    if (!m) throw new Error('could not find revision: <n> in WorldConfig.ts');
    return Number(m[1]);
}

export function generateProt(engineDir: string): { client: string; server: string; revision: number } {
    const read = (p: string) => readFileSync(join(engineDir, p), 'utf8');

    const client = parse(read('src/network/game/client/ClientGameProt.ts'));
    const server = [
        ...parse(read('src/network/game/server/ServerGameProt.ts')),
        ...parse(read('src/network/game/server/ServerGameZoneProt.ts'))
    ];
    const revision = parseRevision(read('src/util/WorldConfig.ts'));

    const header = '// GENERATED by tools/gen-prot.ts from the engine. Do not edit by hand.\n\n';

    return {
        client: header + `export const CLIENT_VERSION = ${revision};\n\n` + renderEnum('ClientProt', client),
        server: header + renderEnum('ServerProt', server) + '\n' + renderSizes(server),
        revision
    };
}

if (import.meta.main) {
    const { client, server } = generateProt(DEFAULT_ENGINE_DIR);
    writeFileSync('src/client/io/ClientProt.ts', client);
    writeFileSync('src/client/io/ServerProt.ts', server);
    console.log('wrote src/client/io/{ClientProt,ServerProt}.ts');
}
