/**
 * Classic 2004scape worldmap Key legend names (index = mapfunction sprite id).
 * Shared by MapView and the map-picker basemap bake / settings.
 *
 * @see https://2004.lostcity.rs/worldmap under the two-page Key legend.
 */
export const WORLDMAP_KEY_NAMES: readonly string[] = [
    'General Store',
    'Sword Shop',
    'Magic Shop',
    'Axe Shop',
    'Helmet Shop',
    'Bank',
    'Quest Start',
    'Amulet Shop',
    'Mining Site',
    'Furnace',
    'Anvil',
    'Combat Training',
    'Dungeon',
    'Staff Shop',
    'Platebody Shop',
    'Platelegs Shop',
    'Scimitar Shop',
    'Archery Shop',
    'Shield Shop',
    'Altar',
    'Herbalist',
    'Jewelery',
    'Gem Shop',
    'Crafting Shop',
    'Candle Shop',
    'Fishing Shop',
    'Fishing Spot',
    'Clothes Shop',
    'Apothecary',
    'Silk Trader',
    'Kebab Seller',
    'Pub/Bar',
    'Mace Shop',
    'Tannery',
    'Rare Trees',
    'Spinning Wheel',
    'Food Shop',
    'Cookery Shop',
    '???',
    'Water Source',
    'Cooking Range',
    'Skirt Shop',
    'Potters Wheel',
    'Windmill',
    'Mining Shop',
    'Chainmail Shop',
    'Silver Shop',
    'Fur Trader',
    'Spice Shop'
];
