import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';

import type { CookSurfaceKind, CookSurfaceLoc } from '../../src/bot/data/cookSurfaceTypes.js';
import { Reader, bridgedLevel, forEachLoc, loadLocTypes, loadMapsquares, parseLands } from '../nav/lib.js';

const ENGINE = process.env.ENGINE_DIR ?? join(homedir(), 'code', 'lostcity-dev', 'engine');
const OUT = 'src/bot/data/cookSurfaceLocs.ts';

/** Loc types carrying `category=cooking_oven` or `cooking_fire` in content, minus `fire`.
 *  Why: `fire` is the player-lit one; it never appears in the map pack and Locs.query finds it live. */
const COOK_SURFACE_KINDS: Readonly<Record<string, CookSurfaceKind>> = {
    range: 'oven',
    loc_2729: 'oven',
    loc_2730: 'oven',
    loc_2731: 'oven',
    cooksquestrange: 'oven',
    fireplace: 'fire',
    grandfireplace: 'fire',
    grandfireplace_oldbrick: 'fire',
    fireplacecookingpot: 'fire'
};

type Row = CookSurfaceLoc;

function generate(): string {
    const { configs } = loadLocTypes(ENGINE);
    const wanted = new Map<number, { name: string; debugname: string; kind: CookSurfaceKind }>();
    for (let id = 0; id < configs.length; id++) {
        const type = configs[id];
        const kind = type?.debugname ? COOK_SURFACE_KINDS[type.debugname] : undefined;
        if (!type?.debugname || !kind) {
            continue;
        }
        wanted.set(id, { name: type.name ?? type.debugname, debugname: type.debugname, kind });
    }
    const missing = Object.keys(COOK_SURFACE_KINDS).filter(d => ![...wanted.values()].some(w => w.debugname === d));
    if (missing.length > 0) {
        console.warn(`no loc type in the pack for: ${missing.join(', ')}`);
    }

    const rows: Row[] = [];
    for (const { mx, mz, land, loc } of loadMapsquares(ENGINE)) {
        const baseX = mx << 6;
        const baseZ = mz << 6;
        const lands = parseLands(new Reader(land));
        forEachLoc(new Reader(loc), instance => {
            const type = wanted.get(instance.locId);
            if (!type) {
                return;
            }
            rows.push({
                x: baseX + instance.x,
                z: baseZ + instance.z,
                level: bridgedLevel(lands, instance.coord, instance.x, instance.z, instance.level),
                name: type.name,
                debugname: type.debugname,
                kind: type.kind
            });
        });
    }
    rows.sort((a, b) => a.level - b.level || a.x - b.x || a.z - b.z);

    const byName = new Map<string, number>();
    for (const r of rows) {
        byName.set(r.name, (byName.get(r.name) ?? 0) + 1);
    }
    console.log(`surfaces=${rows.length} ${[...byName].map(([n, c]) => `${n}=${c}`).join(' ')}`);

    return [
        '/* eslint-disable */',
        '// GENERATED by tools/cooking/gen-cooksurfaces.ts, do not edit.',
        '// Regenerate: bun run gen:cooksurfaces   (drift gate: bun tools/cooking/gen-cooksurfaces.ts --check)',
        "import type { CookSurfaceLoc } from '#/bot/data/cookSurfaceTypes.js';",
        '',
        'export const COOKING_SURFACE_LOCS: readonly CookSurfaceLoc[] = [',
        rows.map(r => `    ${JSON.stringify(r)}`).join(',\n'),
        '];',
        ''
    ].join('\n');
}

const fresh = generate();
if (process.argv.includes('--check')) {
    let current = '';
    try {
        current = readFileSync(OUT, 'utf8');
    } catch {
        // Missing output is stale.
    }
    if (current !== fresh) {
        console.error(`STALE: ${OUT} does not match the map pack — run: bun run gen:cooksurfaces`);
        process.exit(1);
    }
    console.log(`ok: ${OUT} matches the map pack`);
} else {
    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, fresh);
    console.log(`wrote ${OUT}`);
}
