// @rs2b0t/api runtime shim: resolves the ABI the rs2b0t client installs at
// globalThis.__rs2b0t (property names are stable — the bot bundle never
// mangles; see ADR-0004 in the rs2b0t repo). Scripts bundle this in; it
// only works when the bundle runs inside the bot client.
const SUPPORTED_API_VERSION = 1;

const abi = globalThis.__rs2b0t;
if (!abi) {
    throw new Error('@rs2b0t/api: globalThis.__rs2b0t is missing — this script must be loaded inside the rs2b0t bot client (bot.html)');
}
if (abi.apiVersion !== SUPPORTED_API_VERSION) {
    throw new Error(`@rs2b0t/api: client ABI version ${abi.apiVersion} != supported ${SUPPORTED_API_VERSION} — update @rs2b0t/api or the client`);
}

export const {
    apiVersion,
    Execution,
    defineBot,
    registerScript,
    events,
    Game,
    Tile,
    Area,
    Traversal,
    NAV_PURE_WALK,
    NAV_WITH_TELES,
    DirectNavigator,
    Npcs,
    Players,
    Locs,
    GroundItems,
    EntityQuery,
    Npc,
    Player,
    Loc,
    GroundItem,
    Inventory,
    InvItem,
    Equipment,
    Bank,
    withdrawOp,
    Banking,
    depositAllExcept,
    depositMatcher,
    matchesCommonBankLoot,
    shouldBankNow,
    parseBankStrategy,
    PERIODIC_BANK_SETTINGS,
    COMMON_BANK_LOOT,
    RANDOM_EVENT_CASKET_ID,
    NEARBY_BANK_RADIUS,
    resolveBankOpenRoute,
    BANK_LOCATIONS,
    bankDistance,
    bankUnlocked,
    nearestBank,
    nearestUsableBank,
    Shop,
    Trade,
    Skills,
    ChatDialog,
    Quests,
    AcquireTask,
    hasAll,
    held,

    // Tools
    PICKAXES,
    AXES,
    TINDERBOX,
    HAMMER,
    KNIFE,
    CHISEL,
    NEEDLE,
    pickaxeReq,
    axeReq,
    exactTool,
    tinderboxReq,
    toolAttackLevel,
    canWieldTool,
    bestFromTiers,
    bestPickaxe,
    bestAxe,
    toolKeepNames,
    hasToolReq,
    hasAllTools,
    missingToolLabels,
    toolKitLabel,
    toolRestockPlan,
    bankHasBetterGatherTool,
    toolsNeedingEquip,
    bestHeldToolNames,
    surplusHeldToolNames,

    // Tool acquire
    COINS,
    BROKEN_PICKAXE,
    BROKEN_AXE,
    parseToolAcquireMode,
    TOOL_ACQUIRE_OPTIONS,
    TOOL_ACQUIRE_SETTING,
    FORGETFUL_BANK_ODDS,
    FORGETFUL_BANK_SETTING,
    BOB_VENDOR,
    NURMOF_VENDOR,
    GERRANT_VENDOR,
    HARRY_VENDOR,
    GERRANT_ONLY_FISHING,
    VARROCK_ANVIL_STAND,
    VARROCK_ANVIL_BANK,
    PICKAXE_SHOP_COSTS,
    AXE_SHOP_COSTS,
    FISHING_SHOP_COSTS,
    AXE_SMITH_LEVEL,
    AXE_BAR_FOR,
    bestOwnedTier,
    pickaxeShopOffers,
    axeShopOffers,
    bestAffordableShopTier,
    bestSmithableAxe,
    planBrokenToolRepair,
    planPickaxeAcquire,
    planAxeAcquire,
    fishingVendorFor,
    fishingShopCost,
    isFishingBaitPiece,
    withBaitTarget,
    planFishingGearBuys,
    planFishingGearAcquire,
    buyPlansCost,
    fishingGearShopCart,
    planGatherToolAcquire,
    coinsToWithdraw,
    canFundPlan,
    acquireKeepNames,
    shopableMissingFishingGear,

    // Pickpocket
    PICKPOCKET_TARGETS,
    PICKPOCKET_TARGET_NAMES,
    ARDOUGNE_PICKPOCKET_TARGETS,

    // Gathering locations
    DEFAULT_BOOTH_NAME,
    DEFAULT_BOOTH_OP,
    MAP_SQUARE,
    sameMapSquare,
    locationOptions,
    boothFields,
    resolveGatheringLocation,
    FISHING_LOCATIONS,
    FISHING_LOCATION_OPTIONS,
    resolveFishingLocation,
    MINING_LOCATIONS,
    MINING_LOCATION_OPTIONS,
    MINING_LOCATION_OPTION_LABELS,
    miningLocationLabel,
    resolveMiningLocation,
    WOODCUTTING_LOCATIONS,
    WOODCUTTING_LOCATION_OPTIONS,
    resolveWoodcuttingLocation,
    ENT_NPC_IDS,
    ENT_LIFE_TICKS,
    isEntNpcId,
    entNpcOnTile,

    // Fishing methods + mining rocks
    WHIRLPOOL_IDS,
    FISHING_METHODS,
    FISHING_METHOD_OPTIONS,
    ALL_FISHING_GEAR_NAMES,
    resolveFishMethod,
    gearKeepNames,
    hasFishingGear,
    missingFishingGear,
    gearLabel,
    fishingRestockPlan,
    spotMatchesMethod,
    ROCK_TYPES,
    ROCK_OPTIONS,
    GAS_ROCK_IDS,
    GAS_ROCK_TICKS,
    resolveRockIds,

    // Walk destinations
    WALK_DESTINATIONS,
    WALK_OPTIONS,
    resolveDestination,

    // Cow fields
    COW_LOCATIONS,
    COW_LOCATION_OPTIONS,
    AL_KHARID_BANK,
    TOLL_COIN_TARGET,
    isCowFieldLootTile,
    resolveCowLocation,
    nearestCowLocation,
    needsTollCoins,
    shouldBootstrapTollCoins,

    // Rune craft routes
    RUNES,
    RUNE_OPTIONS,
    DEFAULT_RUNE,

    AbstractBot,
    LoopingBot,
    TaskBot,
    TreeBot,
    BranchTask,
    LeafTask,
    reader
} = abi;
